# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(625, 491)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(25, -1, 25, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.txtTitulo = QtWidgets.QLineEdit(self.centralwidget)
        self.txtTitulo.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.txtTitulo.setObjectName("txtTitulo")
        self.verticalLayout_3.addWidget(self.txtTitulo)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.txtDescripcion = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.txtDescripcion.sizePolicy().hasHeightForWidth())
        self.txtDescripcion.setSizePolicy(sizePolicy)
        self.txtDescripcion.setMinimumSize(QtCore.QSize(0, 100))
        self.txtDescripcion.setMaximumSize(QtCore.QSize(16777215, 100))
        self.txtDescripcion.setObjectName("txtDescripcion")
        self.verticalLayout_2.addWidget(self.txtDescripcion)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rtEjecutable = QtWidgets.QLineEdit(self.centralwidget)
        self.rtEjecutable.setReadOnly(True)
        self.rtEjecutable.setObjectName("rtEjecutable")
        self.horizontalLayout.addWidget(self.rtEjecutable)
        self.btnSelectEjectuble = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelectEjectuble.setObjectName("btnSelectEjectuble")
        self.horizontalLayout.addWidget(self.btnSelectEjectuble)
        self.btnLimpiarEjecutable = QtWidgets.QPushButton(self.centralwidget)
        self.btnLimpiarEjecutable.setObjectName("btnLimpiarEjecutable")
        self.horizontalLayout.addWidget(self.btnLimpiarEjecutable)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rtIcono = QtWidgets.QLineEdit(self.centralwidget)
        self.rtIcono.setReadOnly(True)
        self.rtIcono.setObjectName("rtIcono")
        self.horizontalLayout_2.addWidget(self.rtIcono)
        self.btnSelectIcon = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelectIcon.setObjectName("btnSelectIcon")
        self.horizontalLayout_2.addWidget(self.btnSelectIcon)
        self.btnLimpiarIcon = QtWidgets.QPushButton(self.centralwidget)
        self.btnLimpiarIcon.setObjectName("btnLimpiarIcon")
        self.horizontalLayout_2.addWidget(self.btnLimpiarIcon)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.terminal = QtWidgets.QCheckBox(self.centralwidget)
        self.terminal.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.terminal.setObjectName("terminal")
        self.verticalLayout.addWidget(self.terminal)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.lblIcon = QtWidgets.QLabel(self.centralwidget)
        self.lblIcon.setMinimumSize(QtCore.QSize(64, 64))
        self.lblIcon.setMaximumSize(QtCore.QSize(125, 64))
        self.lblIcon.setBaseSize(QtCore.QSize(125, 64))
        self.lblIcon.setText("")
        self.lblIcon.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lblIcon.setObjectName("lblIcon")
        self.horizontalLayout_3.addWidget(self.lblIcon)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.btnCrearAcceso = QtWidgets.QPushButton(self.centralwidget)
        self.btnCrearAcceso.setMinimumSize(QtCore.QSize(125, 100))
        self.btnCrearAcceso.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnCrearAcceso.setSizeIncrement(QtCore.QSize(0, 0))
        self.btnCrearAcceso.setObjectName("btnCrearAcceso")
        self.horizontalLayout_4.addWidget(self.btnCrearAcceso)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 625, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Título"))
        self.label_2.setText(_translate("MainWindow", "Descripción"))
        self.rtEjecutable.setPlaceholderText(_translate("MainWindow", "Ruta Ejecutable"))
        self.btnSelectEjectuble.setText(_translate("MainWindow", "Seleccionar"))
        self.btnLimpiarEjecutable.setText(_translate("MainWindow", "Limpiar"))
        self.rtIcono.setPlaceholderText(_translate("MainWindow", "Ruta Icono"))
        self.btnSelectIcon.setText(_translate("MainWindow", "Seleccionar"))
        self.btnLimpiarIcon.setText(_translate("MainWindow", "Limpiar"))
        self.terminal.setText(_translate("MainWindow", "Terminal?"))
        self.btnCrearAcceso.setText(_translate("MainWindow", "Crear Acceso"))
        self.label_3.setText(_translate("MainWindow", "By C3RBERUSS!"))

